// <auto-generated />
using System;
using ExistingDbScaffolding.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExistingDbScaffolding.Migrations
{
    [DbContext(typeof(ExistingDbContext))]
    partial class ExistingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExistingDbScaffolding.Data.Item", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("OrderId");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("ExistingDbScaffolding.Data.Order", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("Total");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("ExistingDbScaffolding.Data.Item", b =>
                {
                    b.HasOne("ExistingDbScaffolding.Data.Order", "Order")
                        .WithMany("Item")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Item__OrderId__38996AB5");
                });
#pragma warning restore 612, 618
        }
    }
}
